import { motion } from "framer-motion";
import {
  AlertTriangle,
  ShieldAlert,
  Radar,
  Clock,
  MapPin
} from "lucide-react";

export default function Alerts() {
  const alerts = [
    {
      id: 1,
      title: "Weapon Detected",
      location: "Main Entrance Gate",
      time: "10:25 IST",
      level: "HIGH",
      icon: <ShieldAlert />,
    },
    {
      id: 2,
      title: "Unauthorized Access",
      location: "Restricted Server Wing",
      time: "10:35 IST",
      level: "HIGH",
      icon: <AlertTriangle />,
    },
    {
      id: 3,
      title: "Suspicious Movement",
      location: "Zone A – Cargo Bay",
      time: "10:15 IST",
      level: "MED",
      icon: <Radar />,
    },
    {
      id: 4,
      title: "Crowd Surge Detected",
      location: "Public Lobby",
      time: "10:50 IST",
      level: "LOW",
      icon: <Radar />,
    },
  ];

  const levelStyles = {
    HIGH: "border-red-600 text-red-500 bg-red-500/5",
    MED: "border-orange-500 text-orange-400 bg-orange-500/5",
    LOW: "border-blue-500 text-blue-400 bg-blue-500/5",
  };

  return (
    <div className="min-h-screen bg-[#020408] text-slate-200 p-10">
      
      {/* ================= HEADER ================= */}
      <div className="mb-10">
        <h1 className="text-3xl font-black uppercase tracking-tight">
          Alert Intelligence Feed
        </h1>
        <p className="text-gray-500 mt-2">
          Real-time threat notifications generated by Bharat Surveillance Grid
        </p>
      </div>

      {/* ================= STATUS BAR ================= */}
      <div className="flex items-center gap-4 mb-8 text-xs font-mono text-green-500">
        <span className="relative flex h-2 w-2">
          <span className="animate-ping absolute inline-flex h-full w-full rounded-full bg-green-400 opacity-75"></span>
          <span className="relative inline-flex rounded-full h-2 w-2 bg-green-500"></span>
        </span>
        LIVE ALERT STREAM // ENCRYPTED CHANNEL
      </div>

      {/* ================= ALERT GRID ================= */}
      <div className="grid grid-cols-1 md:grid-cols-2 xl:grid-cols-3 gap-6">
        {alerts.map((alert, index) => (
          <motion.div
            key={alert.id}
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ delay: index * 0.08 }}
            className={`relative border ${levelStyles[alert.level]} rounded-2xl p-6 backdrop-blur-xl`}
          >
            {/* LEVEL TAG */}
            <span className="absolute top-4 right-4 text-[10px] font-bold tracking-widest">
              {alert.level} THREAT
            </span>

            {/* ICON */}
            <div className="mb-4">{alert.icon}</div>

            {/* TITLE */}
            <h3 className="text-lg font-bold mb-2">
              {alert.title}
            </h3>

            {/* META */}
            <div className="space-y-1 text-xs text-gray-400">
              <div className="flex items-center gap-2">
                <MapPin size={14} /> {alert.location}
              </div>
              <div className="flex items-center gap-2">
                <Clock size={14} /> {alert.time}
              </div>
            </div>

            {/* ACTION */}
            <button className="mt-5 w-full py-2 rounded-lg border border-white/10 text-xs font-bold uppercase tracking-widest hover:bg-white/5 transition">
              Analyze Threat
            </button>
          </motion.div>
        ))}
      </div>
    </div>
  );
}
